cidr: 192.168.0.0/16

region: ap-southeast-1

availability_zones:
  - ap-southeast-1a
  - ap-southeast-1b

network_tiers:
  - name: web
    public: true
  - application
  - name: management
    public: true
  - database

network_traffic_rules:
  - source_tier: internet
    destination_tier: web
    traffic_type: https
  - source_tier: web
    destination_tier: application
    traffic_type: https
  - source_tier: application
    destination_tier: database
    traffic_type: postgresql

  - source_tier: remote_management
    destination_tier: management
    traffic_type: ssh
  - source_tier: management
    destination_tier: all
    traffic_type: ssh

  - source_tier: all
    destination_tier: internet
    traffic_type: all

known_traffic_types:
  https: 443
  http: 80
  sftp: 22
  ssh: 22
  mysql: 3306
  mssql: 1433
  postgresql: 5432
  oracle: 1521
  mongodb: 27017

known_cidr_ranges:
  internet: '"0.0.0.0/0"'
  remote_management: 'var.remote_management_cidrs'
